### ISSUE TITLE
UI Icons

### ISSUE THREAD

**Issue by i1Zeus** [EnabApp/core#23]
Ui Icons in the following component need attention:
DropDown + Close Button + Input

**Comment by Gruce** [comment]
Hello @i1Zeus  @a7med3bd ,

![image](https://user-images.githubusercontent.com/5357529/189180277-a45f6700-11df-4d61-8f94-9486549b25bd.png)

Icon of app name is not showing full name which is conflicting me.

**Comment by i1Zeus** [comment]
Hey @Gruce  how it is going...
that isn't the real app name it's a demo.
the real app name should show up like this. 👇🏼
<img width="380" alt="image" src="https://user-images.githubusercontent.com/98782046/189182400-364df334-0f54-41d5-9d63-5b74d4e99b2d.png">

hope it's makes sense now that u saw the real thing + this issue wasn't assigned for these buttons hehe 😊😁
have a wonderful day.
