### ISSUE TITLE
Pack Structure

### ISSUE THREAD

**Issue by ste7een** [EnabApp/core#3]
We need to make a **Pack** class  like app class in **appManager** that will content : 

```
pack:[
    id :  ,
    title :   ,
    description :  ,
    discount :   ,
    points:   ,
    owned :    ,  *note
    apps :  [
      if any app was owned the total price of pack will be minus **app.points**
    ],
    services : [
      if any service was owned the total price of  pack will be minus **service.points**
    ]
]
```

*notes : 
Actually i not sure about owned i thing if i buy an pack then will be disappear and just a apps and services inside it will be **owned**

**Comment by Gruce** [comment]
Hello @ste7een,

I agree with you, it's needed because he won't buy it again. Have you made all functionalities in `Supabase`?

**Comment by ste7een** [comment]
Hi @Gruce 
I complete the tables structure in `supabase` but i tried and wonder how we can make like this functionalities 🤔 ?

**Comment by Gruce** [comment]
Hi @ste7een 
What exactly do you need?

**Comment by ste7een** [comment]
Hello again @Gruce 
Actually I don't need  now i will make a function to buy a pack then we need a getters for it .
Thank you .

**Comment by Gruce** [comment]
Good morning @ste7een,
Whenever you want it please don't hesitate to mention me.

Welcome.
